/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ElectricalPanel: typeof import('./src/components/ElectricalPanel.vue')['default']
    ElectricalPanelModal: typeof import('./src/components/ElectricalPanelModal.vue')['default']
    ElectricalPanelModule: typeof import('./src/components/ElectricalPanelModule.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector.vue')['default']
  }
}
